### ISSUE TITLE
Create System Test Template

### ISSUE THREAD

**Issue by lobobeebe** [lobobeebe/zuke-system-test#3]
This involves creating a document from which all system tests will begin. It will be the template that each system test will follow in order to easily conform our system tests.

**Comment by sharadmaheshwari** [comment]
Link to System Test Template:
https://drive.google.com/drive/folders/0B8L89n6lo0DyWmo0SUl1T2JUcXc

Let me know if anybody is having issues accessing the file using link above.

**Comment by lobobeebe** [comment]
Initial thoughts:

I like the setup. Some fields may be a bit redundant or unnecessary for our purposes.

 Although it is the proper process, we do not need a reference number for these documents as we do not have a centralized document number generator. This will be hard to maintain in my opinion and does not grant us a lot of return or use. 

The author field may be difficult because we could have multiple authors. That can stay though. We may just have multiple names in that cell.

Date of creation and review will be very difficult to maintain I think across all documents since we will be reviewing many times. Same with reviewer. Multiple people may be reviewing this.

I would put any pre-conditions before the steps since the pre-condition for step n + 1 would be the result of step n. For instance, our test steps at work normally have:

Pre-Conditions:
X
Y
Z

Step 1: ABC
Step 2: DEF
etc.

I like expected result and actual result but we would need an actual result field per test cycle. I think Test Cycle should be removed because we have the actual results field. I can be swayed on this though.

Overall looks good though. Make any changes you feel are appropriate from this and any that you disagree with should have a comment about why you disagree and we can hash those out.

**Comment by sharadmaheshwari** [comment]
-I agree with you that having reference numbers could be hard to generate and keep in sync, however, my idea behind it was, if we have a reference number, then we can raise bug tickets with the same number (for easy tracking) and assign it to the respective development team. We can get rid of it as of now.

-Date of review and reviewer name are just to make sure that it has been reviewed by somebody, before it is used for actual system testing. If we do not have these fields, then the only other way to track it would be through waffle board. I am okay with that as well. My only concern is that, we will be passing along all these documents to the customer, and therefore having basic information like, date of creation/modification/review would help them track it better. Let me know if you have any other way of dealing this.

-I agree with your idea of having preconditions before the steps. My idea behind having it with every step was just that there might be a case where for a particular step you have a specific precondition. I'll change it.

-Each step will have a different result and therefore I think there is a need for actual result at each step. I did not get what exactly do you want to store in the 'actual result field per test cycle'. Will it just be pass/fail status, or will it be more descriptive? (We are maintaining comments as well as the pass/fail status)

-Test Cycles will only be storing status-Pass/Fail and the idea is to have a Pass status for all the steps in one particular test cycle. By having different test cycles, we can track what was failing in the previous test cycles and after the required code changes, has it lead to failing something else which was initially working fine. Instead of having three test cycles, we can have a single field called 'Status' which stores Pass/Fail, however, since it will be overwritten every time, we won't be able to track the status of previous cycle.

https://drive.google.com/folderview?id=0B8L89n6lo0DyWmo0SUl1T2JUcXc&usp=drive_web&tid=0BwVZj3p1PgcMTEhBY2E3dklXQ00

**Comment by lobobeebe** [comment]
I think for history's sake the entire set of system test files will be filled and stored separately so history will be tracked per fileset, not within a single file. I'm thinking:

| Step        | Description     | Expected Result | Actual Result | Comment |
| :------------------------: |:----------------:|:--------------------:|:----------------:|:-------------:|
| abc                                 | abc                      | abc                              | abc                      | abc                 |
| abc            | abc                      | abc                              | abc                      | abc                 |
| abc            | abc                      | abc                              | abc                      | abc                 |
| abc            | abc                      | abc                              | abc                      | abc

**Comment by sharadmaheshwari** [comment]
Updated as you suggested with slight changes.

https://drive.google.com/folderview?id=0B8L89n6lo0DyWmo0SUl1T2JUcXc&usp=drive_web&tid=0BwVZj3p1PgcMTEhBY2E3dklXQ00

**Comment by lobobeebe** [comment]
Looks good!
